//
//  MediaTranscoderTests.swift
//  EncameraCoreTests
//
//  Exercises MediaTranscoder against committed golden fixtures under Fixtures/.
//  Fixtures are checked in and must not be regenerated by the tests — if one is
//  wrong, revert it rather than rewriting it here.
//

import AVFoundation
import ImageIO
import UniformTypeIdentifiers
import XCTest
@testable import EncameraCore

final class MediaTranscoderTests: XCTestCase {

    private let transcoder = MediaTranscoder()

    private func fixture(_ name: String, _ ext: String) throws -> URL {
        try XCTUnwrap(
            Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "Fixtures"),
            "Missing fixture \(name).\(ext)"
        )
    }

    // MARK: - Pass-through

    func testPassThroughForNativeFormats() async throws {
        let cases: [(name: String, ext: String, type: MediaType)] = [
            ("native", "jpg", .photo),
            ("native", "png", .photo),
            ("native", "heic", .photo),
            ("native", "mov", .video),
            ("native", "mp4", .video),
        ]

        for testCase in cases {
            let url = try fixture(testCase.name, testCase.ext)
            let result = try await transcoder.normalizeForImport(url: url)
            XCTAssertEqual(result.url, url, "\(testCase.ext) should pass through unchanged (no re-encode)")
            XCTAssertEqual(result.mediaType, testCase.type, "\(testCase.ext) should map to \(testCase.type)")
        }
    }

    // MARK: - Image transcoding

    func testTranscodesGifWebpHeifTiffBmpToJpeg() async throws {
        for ext in ["gif", "webp", "heif", "tiff", "bmp"] {
            let url = try fixture("image", ext)
            let result = try await transcoder.normalizeForImport(url: url)

            XCTAssertNotEqual(result.url, url, "\(ext) should be transcoded to a new file")
            XCTAssertEqual(result.mediaType, .photo)
            XCTAssertEqual(result.url.pathExtension, "jpeg", "\(ext) output should be a .jpeg")

            let source = try XCTUnwrap(CGImageSourceCreateWithURL(result.url as CFURL, nil))
            XCTAssertEqual(CGImageSourceGetType(source), UTType.jpeg.identifier as CFString, "\(ext) output should decode as JPEG")
            XCTAssertNotNil(CGImageSourceCreateImageAtIndex(source, 0, nil), "\(ext) JPEG output should be decodable")
        }
    }

    func testRemuxesM4vToMov() async throws {
        let url = try fixture("video", "m4v")
        let result = try await transcoder.normalizeForImport(url: url)

        XCTAssertEqual(result.mediaType, .video)
        XCTAssertEqual(result.url.pathExtension, "mov", "m4v output should be a .mov")

        let asset = AVURLAsset(url: result.url)
        let tracks = try await asset.loadTracks(withMediaType: .video)
        XCTAssertFalse(tracks.isEmpty, "Remuxed MOV should contain a video track")
    }

    // MARK: - Metadata preservation

    func testPreservesOrientationAndCreationDate() async throws {
        let url = try fixture("oriented", "tiff")
        let result = try await transcoder.normalizeForImport(url: url)

        let source = try XCTUnwrap(CGImageSourceCreateWithURL(result.url as CFURL, nil))
        let properties = try XCTUnwrap(CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any])

        let topLevelOrientation = properties[kCGImagePropertyOrientation] as? Int
        let tiff = properties[kCGImagePropertyTIFFDictionary] as? [CFString: Any]
        let tiffOrientation = tiff?[kCGImagePropertyTIFFOrientation] as? Int
        XCTAssertEqual(topLevelOrientation ?? tiffOrientation, 6, "EXIF orientation should survive transcoding")

        let exif = try XCTUnwrap(properties[kCGImagePropertyExifDictionary] as? [CFString: Any])
        let dateTaken = exif[kCGImagePropertyExifDateTimeOriginal] as? String
        XCTAssertEqual(dateTaken, "2021:06:15 12:30:45", "EXIF creation date should survive transcoding")
    }

    // MARK: - Undecodable

    func testUndecodableFileThrowsTypedError() async throws {
        let url = try fixture("corrupt", "tiff")
        do {
            _ = try await transcoder.normalizeForImport(url: url)
            XCTFail("A corrupt image should throw")
        } catch let error as MediaTranscoderError {
            guard case .undecodable = error else {
                return XCTFail("Expected .undecodable, got \(error)")
            }
        }
    }
}
